### PR TITLE
add winget releaser workflow & dependabot

### PR DESCRIPTION
**Pull request by sitiom**
This action automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Houdoku is already in [Winget](https://learn.microsoft.com/en-us/windows/package-manager/winget/), and this workflow will be used to update it.

**Before merging this:**
1. Add a PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN` (or rename the secret name in the workflow).

example

2. Fork https://github.com/microsoft/winget-pkgs under @xgi. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Ensure that you have signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs) for winget-pkgs.
4. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.

The documentation and source code of the action is available [here](https://github.com/vedantmgoyal2009/winget-releaser/).

If you want to see an example of a PR created using this action, see [microsoft/winget-pkgs/pulls (Pull request has been automatically created using 🛫 WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+automatically+created+using+%F0%9F%9B%AB+WinGet+Releaser).

> Migrated from [autoupdate manifest](https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/packages/x/xgi.houdoku.json), see https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/931.

### CODE REVIEW

**Comment by sitiom** [comment]
bump

**Comment by xgi** [comment]
Sorry, but after looking into this I don’t have enough evidence to be confident in the future stability of winget-releaser, and I also don’t really care about Houdoku being available via winget regardless since updates are already available within the client. If anyone wants to include Houdoku in a package repository (programmatically or otherwise) that’s fine with me, but I don’t wish to be the maintainer of it. Thanks.

**Comment by sitiom** [comment]
> I don’t have enough evidence to be confident in the future stability of winget-releaser

What is that supposed to mean?

**Comment by xgi** [comment]
> > I don’t have enough evidence to be confident in the future stability of winget-releaser
>
> What is that supposed to mean?

Just that it's only existed for <2 months & isn't officially associated with Microsoft/winget, so I don't want to have to worry about it breaking and needing an update later -- especially since I'm not really interested in the service it provides for Houdoku to begin with.

**Comment by sitiom** [comment]
> Just that it's only existed for <2 months

[Not really](https://github.com/vedantmgoyal2009/winget-releaser/commit/1fa01fbd59046a46349c45fa9fcb7759d8316f1d), it's just that the "Initial Release" (`v1`) tag was moved to a recent commit and it had just recently branched out from the main repo (it used to reside in the https://github.com/vedantmgoyal2009/vedantmgoyal2009 repo way before, alongside the [winget-pkgs automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) where most packages are updated). It would help ease the CI for other packages if GitHub packages were to use the action, which was the point of this PR.

>  isn't officially associated with Microsoft/winget, so I don't want to have to worry about it breaking and needing an update later

Not really related to stability; breaking changes would still be breaking changes at the end of the day.

**Pull request closed without merging**
