### PR TITLE
Select language of the chapter while reading

### PR DESCRIPTION
**Pull request by rootBrz**
Implemented selection of translation of the chapter while reading it.
Shows only languages chosen in settings, if none selected shows all.
Added "Vol." because some sites has wrong volume set for chapter, or none set at all.

image

### CODE REVIEW

**Comment by rootBrz** [comment]
Also made the menu less cluttered by displaying only preferred language per chapter, because now you can select it in reader. If the language is missing, then a second preferred display and so on. If there is no preferred languages selected, then all languages displayed.

image
image

**Comment by xgi** [comment]
Thanks, I really like this! I think being able to switch between different versions of the same chapter is very useful. I'll merge this, but there are a few parts I'm going to change:
- I don't agree with only showing one language per chapter in the table. Mainly because I don't view the "chapter languages" input as an ordered list. I'd prefer for users to know what languages a chapter is available in from the table.
- Handle case where `groupName` is empty
- I wasn't sure about keeping the page number when swapping languages, but I think it's okay. It might be a bit confusing when pages don't match up between releases, but it doesn't hurt.

Sorry it took me so long to get to this. Thanks!

**Comment by rootBrz** [comment]
>     * I don't agree with only showing one language per chapter in the table. Mainly because I don't view the "chapter languages" input as an ordered list. I'd prefer for users to know what languages a chapter is available in from the table.
Maybe then add this as optional setting? Something like "Show only the main language from "Chapter Languages"" or same language selector as in reader mode, but somewhere in the table. With default behavior the table is really cluttered, and if you're bilingual just like me, you mainly want to read something in one language and switch to another language in the middle of reading if you don't understand something (this is also the reason why page number should be kept, though sometimes it doesn't match).

Thank you for the awesome program!

**Comment by xgi** [comment]
> Maybe then add this as optional setting? Something like "Show only the main language from "Chapter Languages"" or same language selector as in reader mode, but somewhere in the table. With default behavior the table is really cluttered, and if you're bilingual just like me, you mainly want to read something in one language and switch to another language in the middle of reading if you don't understand something (this is also the reason why page number should be kept, though sometimes it doesn't match).
> 
> Thank you for the awesome program!

That's fair, I'll add it as a setting (disabled by default though). My main concern was that I don't want users to think that a chapter isn't available in a language just because they don't see it in the list. There will probably be people who don't even notice the language dropdown in the reader.

I think ultimately this can be communicated better in the chapter table. Having one row per chapter number is a good idea, but we can maybe either have the language dropdown in the row (as you mentioned) or have rows be expandable to show different available versions. But we can save that for later :)

Thanks!

**Pull request merged**
